### ISSUE TITLE
Кастомный интервал опроса API

### ISSUE THREAD

**Issue by filippcanadian** [MihVS/zont_ha#12]
Добрый день!
Думаю, не плохо было бы добавить возможность настраивать интервал опроса API.
Пока работаю через платформу REST из HA, отклик там получается сильно быстрее.

**Comment by MihVS** [comment]
Здравствуйте, намеренно не стал реализовывать эту возможность. Посчитал что раз в минуту достаточно. Для чего чаще? Подумаю, может быть добавлю.

**Comment by MihVS** [comment]
Кастомного интервала опроса не будет. Будем ждать вебхуки от зонта.
