### ISSUE TITLE
Отправка влажности с радиодатчика

### ISSUE THREAD

**Issue by alekslegkih** [MihVS/zont_ha#13]
Сперва огромное спасибо автору за очень полезное дополнение.

Теперь просьба. 

Радио датчик передает температуру, но не передает влажность.
Возможно дополнить  интеграцию? 
А также информацию о  батареи датчика.
Zont отдает всё в одном массиве.

```
[4100] => Array
                        (
                            [temperature] => 19.2
                            [humidity] => 42
                            [battery] => 2.9
                            [rssi] => -53.5
                            [state_time] => 1711358321
                            [state_flags] => 0
                            [sensor_ok] => 1
```

PS. Контролер не заявлен в списке поддерживаемых  "H1V 02"

**Comment by MihVS** [comment]
Здравствуйте, нужно смотреть json от api v2. Можете мне в телегу скинуть файлом, я посмотрю что со влажностью. Вольтаж батарейки зонт добавили в новый апи, но я пока не знаю как это лучше реализовать, самый простой вариант это отдельным датчиком пробрасывать. 

> PS. Контролер не заявлен в списке поддерживаемых "H1V 02"

По идее все модели поддерживаются. А список это на которых я сам лично проверял)

**Comment by iRaschen** [comment]
в версии v0.4.8 радио датчики перестали и температуру паказывать (

**Comment by alekslegkih** [comment]
Причем как то избирательно.
Уличный датчик  МЛ‑711 показывает, а комнатный МЛ-745 (температура + влажность) перестал.
Проводной NTC тоже работает.

**Comment by MihVS** [comment]
https://github.com/MihVS/zont_ha/tree/v0.5.0-beta

пробуем бета, даём обратную связь)

**Comment by MihVS** [comment]
https://github.com/MihVS/zont_ha/tree/v0.5.0

**Comment by iRaschen** [comment]
в 0.5.0 теперь у радиодатчика видет все кроме влажности )
<img width="308" alt="shot 2024-05-09 в 20 37 07" src="https://github.com/MihVS/zont_ha/assets/47774942/944ce9ff-3ca0-4c86-bebd-7b7a0b9c34b1">
В api мой радиодатчик выглядет так:
`
            "io":{
               ....
               "z3k-state":{
                  ....
                  "4110":{
                     "temperature":20.7,
                     "humidity":36,
                     "battery":2.8,
                     "rssi":-58.0,
                     "state_time":1715276216,
                     "state_flags":0,
                     "sensor_ok":true
                  },
                  ....`

**Comment by MihVS** [comment]
> В api мой радиодатчик выглядет так:

В интеграции используется API версии 2.
После выходных со стороны зонта влажность должны добавить. С моей стороны всё готово. Как добавят так и появится. Ждём.

**Comment by alekslegkih** [comment]
Температура заработала.  Появилось напряжение батареи радио датчика. Ждем зонт с влажностью.
Только почти все датчики создались новые, пришлось переписывать все автоматизации :(
![1Screenshot_2](https://github.com/MihVS/zont_ha/assets/136190984/d9acd1a2-5796-4181-82f0-95024bad93f4)

Еще вопрос,  давление отдается как напряжение. Это можно как то поправить?
![1Screenshot_1](https://github.com/MihVS/zont_ha/assets/136190984/b5fcac31-c275-4438-bae1-0381555c7f59)

**Comment by MihVS** [comment]
> Только почти все датчики создались новые

Ну что поделать, надо было удалить интеграцию перезагрузить и установить заново. Не проверял, но возможно поможет.
Пришлось уникальные id сенсоров менять.

> Еще вопрос, давление отдается как напряжение. Это можно как то поправить?

0,8 это давление? или вольтаж? Что за датчик установлен?

**Comment by alekslegkih** [comment]
> 0,8 это давление? или вольтаж? Что за датчик установлен?

0,8 это давление
![Screenshot_3](https://github.com/MihVS/zont_ha/assets/136190984/03db3fcc-5b94-45c9-921a-c1a618dc0ce4)

Аналоговый датчик давления НК3022.

**Comment by MihVS** [comment]
> Аналоговый датчик давления НК3022

Ещё id контроллера дайте (можно в телегу), зонту закину, поправят. С их стороны косяк.

**Comment by MihVS** [comment]
и лучше в отдельной ишью будьте добры по датчику давления)

**Comment by MihVS** [comment]
Влажность с радиодатчиков появилась в НА?

**Comment by iRaschen** [comment]
у меня нет, в апи v2 влажность тоже не вижу
```
{
   "id":4110,
   "name":"Ванна",
   "type":"temperature",
   "status":"ok",
   "value":22.4,
   "unit":"°",
   "triggered":false,
   "battery":2.8,
   "rssi":-51.5
},
```

**Comment by MihVS** [comment]
Можно тогда мне id устройства (контроллера)?

**Comment by iRaschen** [comment]
> Можно тогда мне id устройства (контроллера)?

отправил в ТГ

**Comment by alekslegkih** [comment]
> @alekslegkih, Влажность с радиодатчиков появилась в НА?

Нет, но вроде и обновления не было

**Comment by MihVS** [comment]
> Нет, но вроде и обновления не было

Перезапустите интеграцию и проверьте снова. Проблема была на стороне зонта, не в интеграции.

**Comment by alekslegkih** [comment]
Ура появилась влажность.

![Без имени](https://github.com/MihVS/zont_ha/assets/136190984/cc28600e-4bee-4c65-873f-2fce629a2b3c)

Зонт редиски. Ну было же напряжение батареек в вольтах, нафига в проценты менять.

**Comment by MihVS** [comment]
> Зонт редиски. Ну было же напряжение батареек в вольтах, нафига в проценты менять. При этом в программе в вольтах.

Зонт передаёт в вольтах. Интеграция переводит в проценты, потому что НА так нужно для класса батарейка. Логика пока такая: всё что больше 3.0В это 100%, дальше -10% на каждые 0.1В. Ну и всё что ниже 2.5В это 0%.
