### ISSUE TITLE
Регулировка термостата по температуре теплоносителя.

### ISSUE THREAD

**Issue by AlexandreCherchen** [MihVS/zont_ha#14]
Здравствуйте. 
Спасибо за интеграцию.
Вы мне уже помогли решить проблему с беспроводными датчиками, сейчас решил написать сюда.
У меня Smart 2.0, в нём настроено два отопительных контура, один "отопление" по воздуху с ПИД, второй "подогрев" по ТН.
Оба контура передались в HA и "отопление" работает как надо, а к "подогреву" есть не большой вопрос.
У меня настроено поддерживать фиксированную температуру теплоносителя 35 градусов и термостат добавился с максимальной регулировкой температуры 35 градусов, т.е. "+" больше 35 задать нельзя, хотя в настройках самого контура установлено от 25 до 50 и в самом ZONT можно добавлять и убирать.

![image](https://github.com/MihVS/zont_ha/assets/132154768/6a6fa36a-1004-4ce9-970c-eb1a04f57e1d)
![image](https://github.com/MihVS/zont_ha/assets/132154768/0be51981-fce3-4efa-9dff-886a4f575ea2)

 {
          "id": 8211,
          "name": "Подогрев",
          "status": "ok",
          "active": true,
          "actual_temp": 33.8,
          "is_off": false,
          "target_temp": 35,
          "current_mode": null,
          "target_min": 25,
          "target_max": 50
        }

**Comment by MihVS** [comment]
Здравствуйте. Сам зонт криво передаёт пределы регулировки, поэтому интеграция на данный момент пределы устанавливает по названию контура. В описании интеграции это написано. Обычно лучшим решением регулировать контур по температуре воздуха помещения. А если вам нужны другие пределы (до 75), то добавьте в название контура слово "вода"

**Comment by AlexandreCherchen** [comment]
Спасибо. Извините за невнимательность.
