### ISSUE TITLE
После обновления HA до 2024.5.0 из интеграции пропало все оборудование.

### ISSUE THREAD

**Issue by alekslegkih** [MihVS/zont_ha#15]
Добрый день.
После последнего обновления HA  из интеграции пропало всё оборудование (и контролеры и датчики).
Удаление интеграции и новая установка к положительному результату не привела. Хаб добавляется, ни устройств ни объектов нет.

Система:
- Core: 2024.5.0
- Supervisor: 2024.04.4
- Operating System: 12.2
- Пользовательский интерфейс: 20240501.0
- Версия интеграции ZONT:  0.4.7

Контролеры  **Connect+** и **H1V 02**

**Comment by saSHADE** [comment]
```
2024-05-02 09:02:46.385 ERROR (MainThread) [homeassistant] Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 258, in _handle_refresh_interval
    await self._async_refresh(log_failures=True, scheduled=True)
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 414, in _async_refresh
    self.async_update_listeners()
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 168, in async_update_listeners
    update_callback()
  File "/config/custom_components/zont_ha/sensor.py", line 85, in _handle_coordinator_update
    sensor = self.coordinator.data.get_sensor(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/zont_ha/core/zont.py", line 111, in get_sensor
    all_sensors = device.sensors + device.ot_sensors
                  ^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'sensors'
```

В логах такое есть. Устройство **h1000+ pro**

**Comment by Stanislav-BT** [comment]
Подтверждаю. Данные не обновляются с сегодняшнего дня. Но обновление я не устанавливал на HA…

**Comment by AlexandreCherchen** [comment]
Да, у меня HA установлен в двух местах, один HA обновлён, второй HA нет(core 2024.4.3), на обоих "недоступно".

**Comment by alekslegkih** [comment]
> Подтверждаю. Данные не обновляются с сегодняшнего дня. Но обновление я не устанавливал на HA…

Ну есть вероятность, что совпало. 
Может зонт чего отрезал, хотя обычный php скрипт для телеги продолжает забирать  верные данные.

- Котел в деревне
- 1 этаж: 22.1 °С
- 2 этаж: 23.1 °С
- Улица: 11.8 °С
- Котельная: 18.2 °С
- Давление: 0.8 бар
- t° теплоносителя: 28 °С
- t° ГВС: 32 °С
- Дата: 16:00 02.05.2024

**Comment by Mazannar** [comment]
Подтверждаю, термостат H1V NEW, данные с устройств пропали около 9 часов утра по МСК.

**Comment by AlexandreCherchen** [comment]
У меня пару датчиков подключены к HA не через интеграцию, а через API первой версии, они работают и сейчас без проблем.

**Comment by iRaschen** [comment]
с 9 до 15 видимо у всех были проблемы, но api зонда отвечал нормально который у меня мониторится еще zabbix'om
![Аннотация 2024-05-02 163530](https://github.com/MihVS/zont_ha/assets/47774942/12123171-b553-4690-878f-4f4fdf6b679d)
![Аннотация 2024-05-02 163310](https://github.com/MihVS/zont_ha/assets/47774942/149f4840-7c4d-49c7-ac35-cbb2ca675b4a)

**Comment by EddieSponger** [comment]
Аналогично. 
Сегодня, либо после обновления интеграции до 0.4.7 либо после обновления HA до версии 2024.5.0 перестала работать интеграция. Интеграцию удалил и поставил заново выдает сообщение Неизвестная ошибка при получении устройств ZONT. Новый токен получает.

Приложение на мобиле работает. Приложение для компа - тоже работает. Проблема только с HA

**Comment by Antonio1297** [comment]
После обновления ha интеграция не работает.

**Comment by MihVS** [comment]
Всем привет. Похоже проблемы были на стороне API v2 зонта. На данный момент у меня всё восстановилось. Есть у кого проблемы до сих пор?

**Comment by Antonio1297** [comment]
Добрый день! Нет, все также недоступно. Релоад интеграции, перезагрузка ha не помогает...

**Comment by aeg87** [comment]
> Всем привет. Похоже проблемы были на стороне API v2 зонта. На данный момент у меня всё восстановилось. Есть у кого проблемы до сих пор?

Проблемы с api вчера были. Вчера полдня ресты возвращали пусто, к вечеру восстановилось. 
А вот интеграцию добавить ни вчера, ни сегодня не получается.
```
2024-05-03 08:44:31.499 ERROR (MainThread) [custom_components.zont_ha.config_flow] Что-то пошло не так, неизвестная ошибка. 4 validation errors for AccountZont
devices -> 0 -> heating_circuits -> 0 -> target_min
  value is not a valid float (type=type_error.float)
devices -> 0 -> heating_circuits -> 0 -> target_max
  value is not a valid float (type=type_error.float)
devices -> 0 -> heating_circuits -> 1 -> target_min
  value is not a valid float (type=type_error.float)
devices -> 0 -> heating_circuits -> 1 -> target_max
  value is not a valid float (type=type_error.float)
2024-05-03 08:44:35.514 ERROR (MainThread) [custom_components.zont_ha.config_flow] Что-то пошло не так, неизвестная ошибка. 4 validation errors for AccountZont
```
При этом простейший скрипт вида
`def show_devices():
    url = 'https://lk.zont-online.ru/api/widget/v2/get_devices'
    headers = {'X-ZONT-Client': 'email@dog.ru,
               'X-ZONT-Token': 'токен_сгенерированный_интеграцией'}
    data = ''
    result = requests.post(url, json=data, headers=headers).json()
    return result`
Возвращает 
`{'devices': [{'id': 123456, 'name': 'SMART 2.0', 'model': 'SMART+', 'online': True, 'widget_type': 'z3k', 'heating_circuits': [{'id': 20496, 'name': 'Радиаторы 1 этаж', 'status': 'ok', 'active': False, 'actual_temp': 28.5, 'is_off': False, 'target_temp': 24.0, 'current_mode': 20501, 'target_min': '', 'target_max': ''}, {'id': 8304, 'name': 'Радиаторы 2 этаж', 'status': 'ok', 'active': False, 'actual_temp': 23.2, 'is_off': False, 'target_temp': 23.0, 'current_mode': 20501, 'target_min': '', 'target_max': ''}, {'id': 8293, 'name': 'Тёплый пол', 'status': 'ok', 'active': False, 'actual_temp': 70.3984375, 'is_off': True, 'target_temp': None, 'current_mode': 20501, 'target_min': 5.0, 'target_max': 35.0}, {'id': 4098, 'name': 'ГВС', 'status': 'ok', 'active': False, 'actual_temp': 49.8984375, 'is_off': False, 'target_temp': 45.0, 'current_mode': 20501, 'target_min': 5.0, 'target_max': 75.0}], 'boiler_circuits': [{'id': 20494, 'name': 'Газовый котёл', 'active': False, 'status': 'ok', 'target_temp': 20.0, 'water_min_temp': 15.0, 'water_max_temp': 85.0, 'water_temp': 70, 'dhw_temp': 49.8984375, 'modulation_level': 0.0, 'error_oem': 'Код ошибки 00', 'error_text': 'Потеря связи по цифровой шине'}, {'id': 8203, 'name': 'Электрический котёл', 'active': False, 'status': 'ok', 'target_temp': 20.0, 'water_min_temp': 15.0, 'water_max_temp': 40.0, 'water_temp': 70}], 'heating_modes': [{'id': 20501, 'name': 'Комфорт', 'can_be_applied': True, 'color': '#dd4747'}, {'id': 20502, 'name': 'Эконом', 'can_be_applied': True, 'color': '#73b8d3'}, {'id': 20503, 'name': 'Расписание', 'can_be_applied': True, 'color': '#cbcbcb'}, {'id': 20504, 'name': 'Выключен', 'can_be_applied': True, 'color': '#515151'}, {'id': 8248, 'name': 'Отопление выкл', 'can_be_applied': True, 'color': '#5f7500'}], 'boiler_modes': [{'id': 8211, 'name': 'Основной', 'can_be_applied': True, 'color': '#91b200'}, {'id': 8237, 'name': 'Электро', 'can_be_applied': True, 'color': '#f2c30b'}], 'sensors': [{'id': 0, 'name': 'Напряжение питания', 'type': 'voltage', 'status': 'ok', 'value': 12.5, 'unit': 'В'}, {'id': 4096, 'name': 'Улица', 'type': 'temperature', 'status': 'ok', 'value': 0.9, 'unit': '°'}, {'id': 8194, 'name': 'Котельная', 'type': 'temperature', 'status': 'ok', 'value': 28.5, 'unit': '°'}, {'id': 4100, 'name': 'Спальня', 'type': 'temperature', 'status': 'ok', 'value': 23.2, 'unit': '°', 'battery': 3.0, 'rssi': -70.5}, {'id': 20550, 'name': 'Контроль напряжения питания', 'type': 'voltage', 'status': 'failure', 'value': 12.5, 'unit': 'В'}], 'guard_zones': [], 'custom_controls': [], 'scenarios': [], 'ot_sensors': [{'id': '4097:rml', 'boiler_adapter_id': 4097, 'name': 'ЦШ Модуляция', 'type': 'modulation', 'status': 'ok', 'value': 0.0, 'unit': '%', 'limits': {'high': 0, 'low': 100}}, {'id': '4097:dt', 'boiler_adapter_id': 4097, 'name': 'ЦШ t° ГВС', 'type': 'temperature', 'status': 'ok', 'value': 49.8984375, 'unit': '°', 'limits': {'high': 85.0, 'low': 15.0}}, {'id': '4097:bt', 'boiler_adapter_id': 4097, 'name': 'ЦШ t° ТН', 'type': 'temperature', 'status': 'ok', 'value': 70.3984375, 'unit': '°', 'limits': {'high': 85.0, 'low': 15.0}}]}], 'ok': True}`

**Comment by MihVS** [comment]
@aeg87 в вашем случае всё ясно, поправлю. Спасибо за предоставленную инфу. Зонт немного API поменял. Похоже адекватные максимальные и минимальные температуры стали передавать, это гуд)

**Comment by aeg87** [comment]
Сделал временно у себя в models_zont.py:
вместо
    target_min: float | None
    target_max: float | None
так
    target_min: str | None
    target_max: str | None

Вдруг, кому-то невтерпёж.

**Comment by AlexandreCherchen** [comment]
> Вдруг, кому-то невтерпёж.

Да, спасибо, помогло.
На двух системах заработало. На обновлённой и нет.
После внесения изменений обязательно делать перезапуск HA, перезапуск самой интеграции не помогает.

**Comment by alekslegkih** [comment]
Подтверждаю, после внесения изменений
target_min: str | None
target_max: str | None
новая интеграция создалась, данные появились

**Comment by MihVS** [comment]
https://github.com/MihVS/zont_ha/releases/tag/v0.4.8
Проверяем всё ли ок.

**Comment by Mazannar** [comment]
У меня все ОК, спасибо!

**Comment by EddieSponger** [comment]
v 0.4.8 заработала. Спасибо.
