### ISSUE TITLE
После обновления до версии 0.5.1 перестала работать интеграция

### ISSUE THREAD

**Issue by Sergio164rus** [MihVS/zont_ha#17]
Контроллер Zont H-2000+.
После автоматически предложенного обновления интеграции HA перестал получать данные с контроллера.

![photo_2024-05-12_10-08-20](https://github.com/MihVS/zont_ha/assets/148377910/a9383615-b435-4aa4-a0cb-d3dd028e0b87)
![photo_2024-05-12_10-08-23](https://github.com/MihVS/zont_ha/assets/148377910/9b5521f9-c719-4c79-850d-10507fe0678f)

**Comment by MihVS** [comment]
Начиная с версии 0.5.0 у сенсоров изменились уникальные id. По этой причине если просто обновиться, то создаются новые сенсоры, а старые становятся недоступны. Правильным будет удалить интеграцию из НА и перезагрузиться, а потом установить последнею версию.

**Comment by Sergio164rus** [comment]
> Правильным будет удалить интеграцию из НА и перезагрузиться, а потом установить последнею версию.

После повторной переустановки интеграции снова все заработало.
