### ISSUE TITLE
некорректные пределы регулирования термостата

### ISSUE THREAD

**Issue by andreytel** [MihVS/zont_ha#18]
Добрый день! 
H2000+
контур отопления: контур потребителя, регулирование по теплоносителю.
заданные пределы регулирования в zont 35..70

![IMG_5761](https://github.com/MihVS/zont_ha/assets/170227270/001edd25-b6d2-4c75-a30e-2f2585665abb)

а в HA отображается с пределами регулирования 5..35, и цвет показывает что идет нагрев, а на самом деле нет.

![zont](https://github.com/MihVS/zont_ha/assets/170227270/d2fa5fb4-d2b7-4892-aeca-b3f808718d0e)

**Comment by MihVS** [comment]
Здравствуйте, что бы разобраться, необходимо json ответ от зонт api версии 2 мне в телеграм скинуть.

**Comment by MihVS** [comment]
Исправлено со стороны api zont.

**Comment by fox1047** [comment]
Проблема периодически продолжает проявляться.
```
hvac_modes:
  - heat
  - "off"
min_temp: 40
max_temp: 5
target_temp_step: 1
preset_modes:
  - Комфорт
  - Эконом
  - Расписание
  - Выключен
  - none
friendly_name: Котёл Smart New_Отопление
supported_features: 17
current_temperature: 22.6
temperature: 22
hvac_action: "off"
preset_mode: Комфорт
```

**Comment by MihVS** [comment]
> Проблема периодически продолжает проявляться.

Что значит периодически? Пределы меняются из одного значения в другое сами по себе?

**Comment by fox1047** [comment]
> > Проблема периодически продолжает проявляться.
> 
> Что значит периодически? Пределы меняются из одного значения в другое сами по себе?
По крайней мере на выходных иногда помогала перезагрузка интеграции. После неё пределы становились нормальными. Сейчас не прокатывает.
Если нужна какая то диагностическая информация, то подскажите как её извлечь и я её предоставлю.

**Comment by MihVS** [comment]
Напишите в телегу.

**Comment by MihVS** [comment]
@fox1047  проверяйте, должно работать корректно. Со стороны API поправлено.
