### ISSUE TITLE
Пожелание.

### ISSUE THREAD

**Issue by kainos53** [MihVS/zont_ha#20]
Добрый день.
Спасибо вам за такой замечательный проект. Мой Zont (BAXI) Connect plus заработал без проблем (думаю можно обновить список).

Вопрос в следующем. В оригинальном приложении (сайте) есть статусы показывающие активные\неактивные контуры, горелку и тд.

Подскажите можно ли как то получать эти данные? очень бы хотелось понимать что именно греет zont.

![image](https://github.com/MihVS/zont_ha/assets/172422860/d46a6762-4ea1-409e-a0a8-a2c98f865d7d)

**Comment by MihVS** [comment]
Здравствуйте. Состояния контуров отопления отображаются в НА в статусах термостатов.  Что касается котловых контуров, то не все модели контроллеров передают данную инфу в api v2, но в некоторых моделях сенсоры: уровень модуляции, давление, ошибки котла передаются. Интеграция забирает всё что возможно из api v2 и даже чуточку больше)  В api v1 пока нет желания лезть, да и смысла особого нет, тк интеграция обновляет данные примерно раз в минуту.

**Comment by Nail01** [comment]
Здравствуйте. Спасибо за эту интеграцию. Все прекрасно запустилось на SMART 2.0 PRO + адаптер цифровой шины arderia. Можно добавить в поддерживаемые.
