### ISSUE TITLE
Смена DNS API ZONT

### ISSUE THREAD

**Issue by diemon24** [MihVS/zont_ha#21]
с 16.07 будет смена DNS имени API. Предлагаю заранее подготовить обновление 

![IMG_7161](https://github.com/MihVS/zont_ha/assets/91910101/f6752422-38b5-45e7-a84c-933cc650ec68)
![IMG_7162](https://github.com/MihVS/zont_ha/assets/91910101/8d5f7f5d-3f8b-4b29-bac1-33ee1d859511)

**Comment by iRaschen** [comment]
Если внимательней почитать новость там говорится только про сайт, но насчет api уточнить не мешало бы

**Comment by aeg87** [comment]
> Если внимательней почитать новость там говорится только про сайт, но насчет api уточнить не мешало бы

Последний абзац как раз про апи.

**Comment by MihVS** [comment]
https://github.com/MihVS/zont_ha/tree/v0.5.3

**Comment by diemon24** [comment]
> Если внимательней почитать новость там говорится только про сайт, но насчет api уточнить не мешало бы

Согласен, если повнимательнее почитать, там про API написано 😀

**Comment by diemon24** [comment]
> https://github.com/MihVS/zont_ha/tree/v0.5.3

Михаил, приветствую. Я так понимаю, что учли уже в новой версии?

**Comment by MihVS** [comment]
Версия 0.5.3 работает уже на новом адресе
