### ISSUE TITLE
Добавить статистику

### ISSUE THREAD

**Issue by azharkov78** [MihVS/zont_ha#22]
Добрый день
Можно добавить атрибут статистики для сенсоров?
https://www.home-assistant.io/more-info/statistics/
График не дает построить в карточке без этого.

**Comment by MihVS** [comment]
Здравствуйте, если ещё актуально, то напишите в телеге мне.

**Comment by MihVS** [comment]
https://github.com/MihVS/zont_ha/releases/tag/v0.5.5
