### ISSUE TITLE
Ошибка получения списка объектов при добавлении интеграции

### ISSUE THREAD

**Issue by dkras** [MihVS/zont_ha#23]
При добавлении интеграции корректно получается token, однако после этого выдается ошибка и интеграция не создается.
В логах появляется ошибка:
This error originated from a custom integration.

Logger: custom_components.zont_ha.config_flow
Source: custom_components/zont_ha/config_flow.py:150
integration: MicroLine (documentation)
First occurred: 5:24:53 PM (9 occurrences)
Last logged: 5:44:30 PM

Что-то пошло не так, неизвестная ошибка. 2 validation errors for AccountZont devices -> 0 -> boiler_circuits -> 0 -> error_oem none is not an allowed value (type=type_error.none.not_allowed) devices -> 0 -> boiler_circuits -> 0 -> error_text none is not an allowed value (type=type_error.none.not_allowed)

через web api https://my.zont.online/widget-api/v2 с созданным токеном список объектов получается корректно.

**Comment by MihVS** [comment]
Валидация не проходит, со стороны зонта изменения. Поправим.

**Comment by MihVS** [comment]
https://github.com/MihVS/zont_ha/releases/tag/v0.5.4

**Comment by dkras** [comment]
Ошибка больше не проявляется. Интеграция была успешно добавлена и работает.
Спасибо!
