### ISSUE TITLE
Не удаляется девайс после его удаления в ЛК Зонта

### ISSUE THREAD

**Issue by Kovax2006** [MihVS/zont_ha#24]
Было 3 девайса, машину продал, перевел в другой ЛК и в моем ЛК 2 девайса осталось.
В НА так 3 и висят, не нашел как можно удалить лишнего.
Удалил все сенсоры вручную, но хотелось бы сам девайс удалить.
<img width="284" alt="Снимок экрана 2024-07-27 в 10 16 24" src="https://github.com/user-attachments/assets/9308e8f8-a496-4197-b682-191fc377a750">
<img width="1149" alt="Снимок экрана 2024-07-27 в 10 17 08" src="https://github.com/user-attachments/assets/bb85f929-4d7d-4593-974a-b472a84f366f">

**Comment by MihVS** [comment]
Перезапускать пробовали интеграцию?

**Comment by Kovax2006** [comment]
конечно пробовал

**Comment by MihVS** [comment]
Для удаления девайса, который был удалён в аккаунте зонта, нужно  удалить аккаунт со всеми устройствами в НА и снова добавить.
