### ISSUE TITLE
состояния элемента управления

### ISSUE THREAD

**Issue by Capture456** [MihVS/zont_ha#26]
Добрый день , подскажите  пожалуйста с какой частотой идёт запрос состояния элемента управления ( сложная кнопка ) , ибо у меня состояние меняется только после перезагрузки интеграции .Спасибо

**Comment by MihVS** [comment]
Добрый, состояние всех элементов обновляется примерно раз в минуту.

**Comment by Capture456** [comment]
Спасибо. Ситуация такая что с температурных датчиков информация поступает исправно , а вот с кнопок управления к сожаления нет (бинарный сенсор включено - выключено), эта информация поступает только после перезапуска интеграции

**Comment by Capture456** [comment]
![Screenshot_2024-10-04-08-04-01-993_io homeassistant companion android](https://github.com/user-attachments/assets/3810cbf8-dc7f-4e9b-9262-0b82bee6fd85)
Так же при управлении сигнализации, появляется ошибка.

**Comment by MihVS** [comment]
Ошибка появляется но управление происходит?
По поводу бинарного сенсора напишите мне в телеге, недостаточно данных что бы помочь вам.

**Comment by Capture456** [comment]
Добрый вечер, нет управление при этом не происходит.

**Comment by MihVS** [comment]
https://github.com/MihVS/zont_ha/tree/2024.10.0
