### ISSUE TITLE
validation errors for AccountZont devices

### ISSUE THREAD

**Issue by korneevkonstantin** [MihVS/zont_ha#27]
Перестала работать интеграция.
Переустановил.
Теперь даже не может настроиться.
Это проблема в интеграции или у зонта?

Регистратор: custom_components.zont_ha.config_flow
Источник: custom_components/zont_ha/config_flow.py:150
интеграция: ZONT ([документация](https://github.com/mihvs/zont_ha))
Первое сообщение: 11:53:39 (2 сообщений)
Последнее сообщение: 11:58:36

Что-то пошло не так, неизвестная ошибка. 4 validation errors for AccountZont devices -> 0 -> device_info -> version -> hardware none is not an allowed value (type=type_error.none.not_allowed) devices -> 0 -> device_info -> version -> software none is not an allowed value (type=type_error.none.not_allowed) devices -> 1 -> device_info -> version -> hardware none is not an allowed value (type=type_error.none.not_allowed) devices -> 1 -> device_info -> version -> software none is not an allowed value (type=type_error.none.not_allowed)

**Comment by MihVS** [comment]
Здравствуйте, со стороны зонта ответ не валидный прилетает.  Что-то в апи видимо поменял. Посмотрю

**Comment by MihVS** [comment]
На моих устройствах всё валидно.
Какую версию интеграции используете? Версия НА? В телеграм отправьте ответ от api зонта файлом json.

**Comment by MihVS** [comment]
https://github.com/MihVS/zont_ha/tree/2024.10.1

**Comment by korneevkonstantin** [comment]
> На моих устройствах всё валидно. Какую версию интеграции используете? Версия НА? В телеграм отправьте ответ от api зонта файлом json.

Интеграция:
Началось все на 2024.10.1.
Пробовал и предыдущую, тоже самое.

HA:
Core
2024.10.2
Supervisor
2024.10.0
Operating System
13.1
Пользовательский интерфейс
20241002.3

**Comment by MihVS** [comment]
Обновите интеграцию до версии 2024.10.1
