### ISSUE TITLE
Пожелания по добавлению новых параметров

### ISSUE THREAD

**Issue by ivonderkof** [MihVS/zont_ha#28]
Из POST запроса на https://my.zont.online/api/' (у вас он идет как ZONT_API_URL_ROOT) можно достать новые значения, такие важные параметры как давления теплоносителя в системе, уровень модуляции и напряжение питания.  

1. Напряжение питания: `devices[0].io.voltage`
2. Уровень модуляции(в процентах): `devices[0].io["last-boiler-state"].ot.rml`
3. Давление (используется округление в большую сторону 1.59 -> 1.6): `devices[0].io["last-boiler-state"].ot.wp`

```
{
    "rml": 42,
    "wp": 1.59765625,
}
```

Из запроса на `/api/sim/info_for_user` можно достать текущие параметры и лимиты сим карты:

1. Лимиты: `sim_statuses[0].limits[0]`
Идут в порядке интернет(мб)/смс(кол-во)/звонки(мин)
```
[
    "40/30/30"
]
```

2. Использование лимитов: `sim_statuses[0].usage_counters`
mb - идет округление до двух знаков

```
{
    "mb": 13.738038063049316,
    "sms": 4,
    "calls": 0
}
```

Из обязательных параметров, помимо кукисов для запроса важны следующие заголовки: 

```
X-ZONT-Client
X-ZONT-Client-Version
Content-Type
```
Опытным путем выяснил, что важным является только заголовок `Content-Type` с содержанием `application/json`, тогда ответ возвращается корректный. 

Запрос реагировал положительно на любое значение заголовков `X-ZONT-Client` и `X-ZONT-Client-Version`. 

Как мне кажется, то данные параметры достаточно важны, потому как для уровня модуляции в HA можно создать сенсор, который сможет высчитывать уровень потребления Квт\ч (зная установленные значения), давление теплоносителя важно, т.к можно посылать уведомления о его непредвиденном снижении не как сейчас устроенно в zont только при достижении установленного минимума, а при утечке в n-ное кол-во времени, что позволит предотвратить аварию намного раньше. 

Остальные параметры являются более информационными.

**Comment by MihVS** [comment]
> Из POST запроса на https://my.zont.online/api/' (у вас он идет как ZONT_API_URL_ROOT) можно достать новые значения, такие важные параметры как давления теплоносителя в системе, уровень модуляции и напряжение питания.

Здравствуйте, интеграция использует API версии 2, обратите на это внимание. API v1 слишком неуниверсально.
Напряжение, уровень модуляции, давление интеграция получает, если у вашего устройства нет, то обратитесь в разработчикам зонт что бы они добавили в  API v2 для вашего устройства данные.

>Как мне кажется, то данные параметры достаточно важны, потому как для уровня модуляции в HA можно создать сенсор, который сможет высчитывать уровень потребления Квт\ч

Не забывайте, что интеграция обновляет данные раз в минуту, поэтому учёт энергии не получится. Пока вот так.

>Из запроса на /api/sim/info_for_user можно достать текущие параметры и лимиты сим карты:

По сим карте и прочему, этого в API v2 нет, можете тоже задать вопрос напрямую в зонт.
