### ISSUE TITLE
Предложения

### ISSUE THREAD

**Issue by no157ru** [MihVS/zont_ha#3]
Моя конфигурация:
Контроллер ZONT Smart 2.0 PRO
1) Котловой контур: через реле электрический STOUT, через K-Line и OpenTherm адаптер Mizudo
2) Потребительские контуры: через универсальные порты ввода-вывода и промежуточные реле подключены циркуляционные насосы контуров "Радиаторы 1", "Радиаторы 2" и БКН

Непонятка:
В интеграции zont_ha предел регулирования температуры контура БКН - 35С, хотя в конфигурации ZONT для бойлера уставка 70С. Соответственно при попытке изменить температуру бойлера через HA - она слетает в 35. Наверное нужна настройка пределов регулирования температуры контура через HA

Хотелки:
Хорошо бы добавить (или объяснить как сделать): 
1) кнопки переключения режимов отопления (Комфорт, Эконом, Выключено, Расписание, Лето). У меня сейчас отапливается в основном первый этаж дома и греется бойлер для ГВС, второй этаж держу +14. Когда приезжают гости появляется необходимость поднять второй этаж до комфортных +22. Летом радиаторы надо остановить, но оставить бойлер. Это удобнее переключать кнопкой с заранее заданными правилами игры, а не крутилки каждый раз вертеть.
2) Для котлов у меня есть три режима - "Газ", "Электро" и "Комбо". В комбо газ основной, электро как резерв/дополнение. Но иногда бывает необходимость выбрать конкретный котел и полностью отключить второй (например, профилактика или ремонт какой).

Вопросы:
1) можно ли из API ZONT дергать оповещения и настроить их пересылку через HA и например бота в телеге? Чтобы если давление или температура ушли из допустимого диапазона или еще что пошло не так - чтобы HA уведомлял о проблеме..
2) можно ли заставить ZONT менять свое поведение по показаниям других датчиков, например Zigbee на температуру/влажность/открытие окна/протечки ?

Спасибо.

**Comment by MihVS** [comment]
> Непонятка:
В интеграции zont_ha предел регулирования температуры контура БКН - 35С, хотя в конфигурации ZONT для бойлера уставка 70С. Соответственно при попытке изменить температуру бойлера через HA - она слетает в 35. Наверное нужна настройка пределов регулирования температуры контура через HA

В описании написано что на данный момент пределы температур в НА выставляются по названию. Для воды нужно обозвать контур ГВС или горячая вода например. В следующем обновлении добавлю и ваш БКН.


> кнопки переключения режимов отопления (Комфорт, Эконом, Выключено, Расписание, Лето). У меня сейчас отапливается в основном первый этаж дома и греется бойлер для ГВС, второй этаж держу +14. Когда приезжают гости появляется необходимость поднять второй этаж до комфортных +22. Летом радиаторы надо остановить, но оставить бойлер. Это удобнее переключать кнопкой с заранее заданными правилами игры, а не крутилки каждый раз вертеть.

В НА добавляются термостаты контуров отопления и там есть возможность выбора режима. Сами режимы создаются в интерфейсе ZONT. можно создать какой душе угодно и он проброситься в НА.


> Для котлов у меня есть три режима - "Газ", "Электро" и "Комбо". В комбо газ основной, электро как резерв/дополнение. Но иногда бывает необходимость выбрать конкретный котел и полностью отключить второй (например, профилактика или ремонт какой).

Опять же в [описании](https://github.com/MihVS/zont_ha?tab=readme-ov-file#кастомные-элементы). Для управления котлами можете в интерфейсе ZONT создать кастомные элементы (кнопка или сложная кнопка) и повесить на них включение и отключение котла.


> можно ли из API ZONT дергать оповещения и настроить их пересылку через HA и например бота в телеге? Чтобы если давление или температура ушли из допустимого диапазона или еще что пошло не так - чтобы HA уведомлял о проблеме.

Нет такой возможности. Вероятно в будущем в API ZONT добавятся аварийные сенсоры и тогда HA будет видеть аварии устройства.


> можно ли заставить ZONT менять свое поведение по показаниям других датчиков, например Zigbee на температуру/влажность/открытие окна/протечки ?

Тут так же можно через кастомные элементы реализовать какой-нибудь функционал. Ну а подменить датчик температуры зонтовский на зигбишный например не получиться. Думаю это и правильно, надёжная работа контроллера отопления превыше всего)
