### ISSUE TITLE
Температура в карточке термостата в Фаренгейтах

### ISSUE THREAD

**Issue by KirillCH2** [MihVS/zont_ha#30]
Добрый день! Температура отображается в фаренгейтах только в карточке термостата, в сенсорах в цельсиях. Настроек не нашел ни в HASS ни в зонте. Версия Вашего модуля и HASS последние на текущий день.

**Comment by Foxch2** [comment]
![2024-11-11_105544](https://github.com/user-attachments/assets/e465c513-db42-4c9a-9797-af67d66ab84a)
все температурные показатели в цельсиях, а на карточке термостата - F
в чем может быть проблема?

**Comment by MihVS** [comment]
Здравствуйте, это НА вам так ставит. Ищите в настройках НА.

**Comment by KirillCH2** [comment]
У этого объекта нет настроек, везде посмотрел вроде. Если точно знаете где, подскажите.
