### ISSUE TITLE
Перестали приходить данных после обновления прошивки 

### ISSUE THREAD

**Issue by ggr3gg** [MihVS/zont_ha#31]
Термостат H-1V NEW, на прошивке 407 все данные попадали в HA, управление работало. Но был установлен датчик давления теплоносителя, и для его поддержки пришлось обновиться до 486 версии, после этого данные перестали отображаться в HA. В отладке HA  тоже не нашел никаких упоминаний. Удалил интеграцию и запросил новый токен API, но устройств не найдено. В вебе zont видно что обращение по API было. В чем может быть проблема? Отключен API на прошивке 486?

**Comment by MihVS** [comment]
Здравствуйте, напишите в службу поддержки zont. Проблема похоже на их стороне. От API не приходят данные.

**Comment by ggr3gg** [comment]
Михаил, здравствуйте. Добавленный в конфигурацию новый датчик MLD-10.01 не имел идентификатора, уже исправили API.
