### ISSUE TITLE
Пожелания

### ISSUE THREAD

**Issue by DaN66O** [MihVS/zont_ha#5]
Есть пожелание :)
1. Для батарейный датчиков добавить напряжение батареи или процент заряда 
2. Добавить время работы котла или хотя бы состояние ( работает / не работает )

**Comment by artemsiberiangit** [comment]
Я тут не в тему, но просто хочу сказать автору что бы не бросал это дело, очень полезно, я еще пока не цеплял это все, но в скором времени собираюсь :)

**Comment by MihVS** [comment]
> Для батарейный датчиков добавить напряжение батареи или процент заряда

У меня нет таких датчиков. Если у вас есть возможность, то в телеге скиньте мне json ответ от api, и я посмотрю что можно сделать.

> Добавить время работы котла или хотя бы состояние ( работает / не работает )

есть датчик котловой, уровень модуляции горелки, скорее всего он вам подойдёт. Но тут есть одно но) пока не все устройства передают эти датчики котловые в новый api. Разработчики zont обещали добавить. Пока ждём, а потом посмотрим что можно сделать.

**Comment by DaN66O** [comment]
> Если у вас есть возможность, то в телеге скиньте мне json ответ от api

```
      "rf_status": {
        "s_%45822%": {
          "name": "Топочная",
          "time": 1708193989,
          "type": "MLT",
          "temp": 21.6,
          "bat_v": 2.9296875,
          "bat": 14,
          "dbm": -47,
          "slot": 0,
          "version": null,
          "uninitialized": false
        },
        "s_%512768%": {
          "bat": 15,
          "bat_v": 2.98828125,
          "dbm": -48,
          "temp": 20.1,
          "time": 1708193771,
          "type": "MLT",
          "name": "Гостиная",
          "slot": 3,
          "version": 4142,
          "uninitialized": false
        },
```

**Comment by spawnax** [comment]
Добрый день, у меня под модбасу подключена вент-установка туркова, сейчас её датчики мигригруют в ХА как вольтаж, лучше наверное сделать их миграцию в зависимости от единицы измерения, вот для примера скорость вентилятора:
   - physical_input_num: 148704
        name: Турков. Мощность вытяжки
        upper_threshold: null
        lower_threshold: null
        active_level_timeout: 1
        inactive_level_timeout: 2
        setting_register: 0
        notification_list: []
        sensor_type: 0
        recovery_list: []
        upper_notification_list: []
        impulse_frequency: 1
        calibration: 9309
        position: 5
        units: 7
        voltage: -1
        id: 9310
В зонте выбрана единица измерения %
Второй пример с давлением:
      - physical_input_num: 147712
        name: Турков. Давление в вытяжке
        upper_threshold: 0
        lower_threshold: 0
        active_level_timeout: 1
        inactive_level_timeout: 2
        setting_register: 0
        notification_list: []
        sensor_type: 0
        recovery_list: []
        upper_notification_list: []
        impulse_frequency: 1
        calibration: 9247
        position: 3
        units: 2
        voltage: -1
        id: 9248

тут в качестве единицы измерения выбрана "Бар"

**Comment by Kovax2006** [comment]
H1500 PRO - не работает управление, все серое, только состояние.
