### ISSUE TITLE
Переключение режимов отопления в НА

### ISSUE THREAD

**Issue by Stanislav-BT** [MihVS/zont_ha#6]
Добрый день!
Строю систему управления умного дома на контроллере ZONT H2000+pro, трех блоках расширения к нему + HA.
Большое спасибо за Ваш компонент, это необходимая интеграция для каждого пользователя ЗОНТа)
Установил 19.02.24 Ваш компонент для интеграции зонта в HA.
Работает отлично, благодарю за труды.
Пару моментов, что я заметил, так сказать обратная связь:
1) Режимы отопления передаваемые в НА, если их менять непосредственно в панели управления контура на НА, меняются только на одном выбранном контуре. 
Т.е. к примеру, у меня построено три контура отопления (1 этаж, 2 этаж, и Гараж). Создано несколько режимов отопления, в каждом из которых на ЗОНТе задействованы все контуры. 
Теперь я в НА выбираю на одном из контуров запрограммированный ранее режим отопления (допустим "Общий", при котором в настройках зонта выставлена температура каждого контура) и данный режим включается непосредственно на том контуре, который выбран в НА. Остальные же контуры остаются работать на заданной ранее температуре и на них автоматом не выбирается выбранный режим. например как это задумано на ЗОНТе.
Думаю это баг) Т.е. режим должен переключаться на всех контурах автоматом, которые задействованы в нем.
2) При попытке выключить контур отопления в НА, нажав на иконку кнопки выключения под изображением термостата контура, получаю сообщение:
"Не удалось вызвать службу climate/set_hvac_mode. Изменение HVAC не поддерживается ZONT. Контур управляется котлом"
Думаю это связано с тем, что данный контур задействован как раз в режиме отопления, в котором присутствуют и другие контуры. Хотя кнопка выключения контура нужная, и хотелось, чтобы она работала)
3) И вопрос по обновлению интеграции на новую версию, когда таковые будут выходить... В инструкции на GIT нет такой информации, поэтому хотелось бы уточнить как это делать?)

**Comment by MihVS** [comment]
> Большое спасибо за Ваш компонент, это необходимая интеграция для каждого пользователя ЗОНТа)

Звезду компоненту не поленитесь поставить ;)

> Думаю это баг) Т.е. режим должен переключаться на всех контурах автоматом, которые задействованы в нем.

Нет это не баг, так и задумано. А если мне нужно поменять режим только на одном контуре?) Создайте кастомный элемент в зонте и привяжите этот функционал к нему. Ну или с помощью автоматизации НА реализуйте.

>  Хотя кнопка выключения контура нужная, и хотелось, чтобы она работала)

Внимательно читайте описание компонента и подсказку в НА. КОНТУР ОТОПЛЕНИЯ УПРАВЛЯЕТСЯ КОТЛОМ! на данный момент нет такой возможности.

> В инструкции на GIT нет такой информации, поэтому хотелось бы уточнить как это делать?)

Ну инструкция для пользования home assistan думаю находится у них) 
Если через HACS ставили, то там обновы прилетают. Если вручную, то и обновляйте вручную.

**Comment by Stanislav-BT** [comment]
Если через HACS ставили, то там обновы прилетают, да, именно так и ставил.
Следовательно руками не нужно будет ничего делать, обнова установится автоматом, верно?

По остальным пунктам понятно, спасибо за быстрый ответ)

**Comment by Stanislav-BT** [comment]
По следам совета создания создания кастомного элемента.
Сделано. Создал на зонте доп элемент управления через сценарии, который включает и отключает общий режим отопления.
Однако данные новые элементы не появляются в интеграции ЗОНТа в НА.
В настройках интеграции стоит галка:
"Home Assistant будет автоматически добавлять новые обнаруженные устройства ZONT"
Пробовал перезапускать интеграцию по кнопке соответствующей, а также перезагружать сам ЗОНТ, но новые добавленные пункты управления так и не появляются в НА...
Куда копать чтобы решить этот вопрос?

**Comment by MihVS** [comment]
> Создал на зонте доп элемент управления через сценарии

Сценарии не прокидываются в НА.

**Comment by Stanislav-BT** [comment]
> > Создал на зонте доп элемент управления через сценарии
> 
> Сценарии не прокидываются в НА.

нет, вопрос не в сценариях)

Есть элемент управления (кнопка простая). И вот ее не видно)

Для информации у меня ранее уже были сделаны несколько кнопок, которые также завязаны на др сценариях, и они норм отображаются в НА и работают там.

**Comment by MihVS** [comment]
> Есть новый элемент управления (кнопка простая). И вот ее не видно в НА

Нужно смотреть ответ от ZONT.

>  можно ли как то обновить список устройств в НА от зонта в ручном режиме

три точки справа и перезагрузить. Ручного нет, только принудительно обновить конфиг. Можете попробовать перезайти.

**Comment by Stanislav-BT** [comment]
> Нужно смотреть ответ от ZONT.

Могу посмотреть и прислать код ответа... Где его увидеть? Что скопировать? Куда зайти?

**Comment by MihVS** [comment]
В телегу напишите, там обсудим.

**Comment by Stanislav-BT** [comment]
написал
